import fs from 'fs';
import path from 'path';

/* eslint-disable no-console */

// Fetches an instance's public config from <url>/node-api/config and writes it as raw KEY=value
// lines (default ./.env.tmp) consumed by the dev server (via dotenv-cli) and the container
// entrypoint (via a `while IFS='=' read` loop — values are NOT quoted, so they are not `source`-safe).
//
// Usage:
//   node fetch.js <alias> [--omit-local-envs] [--out=<path>]
//
//   <alias>            key from registry.json (e.g. "eth")
//   --omit-local-envs  drop the localEnvs keys entirely instead of substituting their local
//                      values — used in the container so the deployment's own APP_* survive
//   --out=<path>       output file (default ./.env.tmp, relative to cwd)

type Registry = Record<string, string>;
type EnvsRules = { localEnvs: Record<string, string>; ignoredEnvs: Array<string> };

function readJson<T>(fileName: string): T {
  return JSON.parse(fs.readFileSync(path.resolve(__dirname, fileName), 'utf8')) as T;
}

function parseArgs() {
  const args = process.argv.slice(2);
  const positional = args.filter((arg) => !arg.startsWith('--'));
  const flags = args.filter((arg) => arg.startsWith('--'));

  const out = flags.find((flag) => flag.startsWith('--out='))?.replace('--out=', '') ?? '.env.tmp';

  return {
    alias: positional[0],
    omitLocalEnvs: flags.includes('--omit-local-envs'),
    out,
  };
}

async function run() {
  const { alias, omitLocalEnvs, out } = parseArgs();

  if (!alias) {
    console.log('🚨 No instance alias provided. Usage: node fetch.js <alias> [--omit-local-envs] [--out=<path>]');
    process.exit(1);
  }

  const registry = readJson<Registry>('./registry.json');
  const { localEnvs, ignoredEnvs } = readJson<EnvsRules>('./envs-rules.json');

  const instanceUrl = registry[alias];
  if (!instanceUrl) {
    console.log(`🚨 No instance with alias "${ alias }" found in registry.json. Exiting...`);
    process.exit(1);
  }

  console.log(`🌀 Fetching config for "${ alias }" from ${ instanceUrl }/node-api/config ...`);

  const response = await fetch(`${ instanceUrl }/node-api/config`);
  if (!response.ok) {
    console.log(`🚨 Request failed with status ${ response.status }. Exiting...`);
    process.exit(1);
  }
  const instanceConfig = await response.json() as Record<'envs', Record<string, string>>;

  const localEnvKeys = Object.keys(localEnvs);

  const entries = Object.entries(instanceConfig.envs)
    // drop deprecated / build-time vars and the local-only keys (we set them ourselves below)
    .filter(([ key ]) => !ignoredEnvs.includes(key) && !localEnvKeys.includes(key));

  // localEnvs: substitute local values for dev, or omit entirely for the container
  if (!omitLocalEnvs) {
    entries.push(...Object.entries(localEnvs));
  }

  const sorted = entries.sort(([ a ], [ b ]) => a.localeCompare(b));

  // Raw KEY=value lines (no surrounding quotes), matching the format dotenv-cli expects —
  // the same format the committed preset files use. The container entrypoint reads this via a
  // `while IFS='=' read` loop (not `source`), so embedded quotes/spaces stay literal.
  const content =
    `# Auto-generated by tools/dev-server/fetch.ts — do not edit.\n` +
    `# Source: ${ instanceUrl }/node-api/config (alias "${ alias }")\n` +
    '\n' +
    sorted.map(([ key, value ]) => `${ key }=${ value }`).join('\n') +
    '\n';

  const outPath = path.resolve(process.cwd(), out);
  fs.writeFileSync(outPath, content);

  console.log(`✅ Wrote ${ sorted.length } envs to ${ outPath }`);
}

run();
