export enum QueryKeys {
  csrf = 'csrf',
  profile = 'profile',
  txsValidate = 'txs-validated',
  txsPending = 'txs-pending',
  tx = 'tx',
  txInternals = 'tx-internals',
  txLogs = 'tx-logs',
  txRawTrace = 'tx-raw-trace',
  txTokenTransfers = 'tx-token-transfers',
  blockTxs = 'block-transactions',
  block = 'block',
  blocks = 'blocks',
  chartsTxs = 'charts-txs',
  chartsMarket = 'charts-market',
}
