/* eslint-disable no-console -- this is a CLI whose entire job is to print a report to stdout */
import fs from 'fs';

import { buildFileRows } from './analyze';
import { DEFAULT_BASE_REF, DEFAULT_MAX_COMPLEXITY, DEFAULT_MAX_CRAP } from './config';
import { readCoverage } from './coverage';
import type { CoverageData } from './coverage';
import { getAllSourceFiles, getChangedFiles, getChangedLineRanges, rangesOverlap, resolveBaseCommit } from './diff';
import { generateCoverage } from './generate-coverage';
import type { CoverageRequest } from './generate-coverage';
import { fileContainsJsx } from './jsx';
import type { ReportRow, Thresholds } from './report';
import { formatTable, isOffender } from './report';
import { isInScope } from './scope';

// Two independent axes, mirroring vitest. Selection = which functions to score; coverage = how the
// coverage half is obtained. Any selection combines with any coverage source.
//
// Selection:
//   full (default)     — every in-scope src/** function (ticket-04 calibration; a repo-wide report)
//   focused (<path...>)— every function in the given files
//   diff (--changed)   — only functions a changed line falls within, vs the base ref
//
// Coverage:
//   'generate' (default) — run vitest to produce coverage for the selection's scope
//   'file'  (--coverage-file <path>) — consume a prebuilt coverage-final.json, skip vitest (CI)
//   'off'   (--no-coverage)          — skip coverage, complexity gate only
type CoverageMode = 'generate' | 'file' | 'off';

interface CliOptions {
  baseRef: string;
  diffSelected: boolean;
  maxComplexity: number;
  maxCrap: number;
  coverageMode: CoverageMode;
  coverageFile: string | undefined; // set only when coverageMode === 'file'
  verbose: boolean;
  focusPaths: Array<string>;
}

const USAGE = `Usage:
  test:code-complexity [--max-complexity <n>] [--max-crap <n>]
                       [--coverage-file <path> | --no-coverage]
      Full-repo mode (default): score every in-scope src/** function.

  test:code-complexity <path...> [...]     Focused mode: score every function in the given files.

  test:code-complexity --changed[=<ref>] [--base <ref>] [...]
      Diff mode: gate only functions the diff touches vs the base ref (default origin/main).

  Coverage is generated by running vitest (scoped to the selection) unless --coverage-file supplies
  a prebuilt report (the CI path, skips vitest) or --no-coverage skips it (complexity gate only).
  Vitest output is hidden by default; --verbose streams it live.`;

function parseArgs(argv: ReadonlyArray<string>): CliOptions {
  const options: CliOptions = {
    baseRef: DEFAULT_BASE_REF,
    diffSelected: false,
    maxComplexity: DEFAULT_MAX_COMPLEXITY,
    maxCrap: DEFAULT_MAX_CRAP,
    coverageMode: 'generate',
    coverageFile: undefined,
    verbose: false,
    focusPaths: [],
  };

  for (let index = 0; index < argv.length; index++) {
    const arg = argv[index];
    const readValue = (inline: string | undefined): string => {
      if (inline !== undefined) return inline;
      const next = argv[++index];
      if (next === undefined) throw new Error(`Missing value for ${ arg }`);
      return next;
    };
    const readNumber = (inline: string | undefined): number => {
      const raw = readValue(inline);
      const value = Number(raw);
      if (!Number.isFinite(value) || value < 1) throw new Error(`Invalid value for ${ arg }: ${ raw }`);
      return value;
    };
    const inlineValue = (prefix: string): string | undefined =>
      arg.startsWith(`${ prefix }=`) ? arg.slice(prefix.length + 1) : undefined;

    if (arg === '--help' || arg === '-h') {
      console.log(USAGE);
      process.exit(0);
    } else if (arg === '--verbose') {
      options.verbose = true;
    } else if (arg === '--no-coverage') {
      options.coverageMode = 'off';
    } else if (arg.startsWith('--coverage-file')) {
      options.coverageMode = 'file';
      options.coverageFile = readValue(inlineValue('--coverage-file'));
    } else if (arg.startsWith('--changed')) {
      options.diffSelected = true;
      const inline = inlineValue('--changed');
      if (inline !== undefined) options.baseRef = inline;
    } else if (arg.startsWith('--base')) {
      options.diffSelected = true;
      options.baseRef = readValue(inlineValue('--base'));
    } else if (arg.startsWith('--max-complexity')) {
      options.maxComplexity = readNumber(inlineValue('--max-complexity'));
    } else if (arg.startsWith('--max-crap')) {
      options.maxCrap = readNumber(inlineValue('--max-crap'));
    } else if (arg.startsWith('-')) {
      throw new Error(`Unknown flag: ${ arg }\n${ USAGE }`);
    } else {
      options.focusPaths.push(arg);
    }
  }

  return options;
}

function normalizeDisplayPath(filePath: string): string {
  return filePath.replace(/\\/g, '/').replace(/^\.\//, '');
}

function readFile(filePath: string): string {
  return fs.readFileSync(filePath, 'utf8');
}

function thresholdsOf(options: CliOptions): Thresholds {
  return { maxComplexity: options.maxComplexity, maxCrap: options.maxCrap };
}

// Resolve coverage from the chosen mode. `request` steers generation; it is ignored for 'file' and
// 'off'. `anyNeedsCoverage` short-circuits generation: when nothing in the selection gets the CRAP
// half (see coverageApplies) there is nothing coverage could inform, so we skip vitest and return
// null instead of running it for numbers that would be discarded.
function resolveCoverage(options: CliOptions, request: CoverageRequest, anyNeedsCoverage: boolean): CoverageData | null {
  switch (options.coverageMode) {
    case 'off':
      return null;
    case 'file':
      // coverageFile is always set when the mode is 'file' (parseArgs reads its value).
      return readCoverage(options.coverageFile as string);
    case 'generate':
      return anyNeedsCoverage ? generateCoverage(request, { verbose: options.verbose }) : null;
  }
}

// Whether a source file has a co-located vitest spec, by naming convention
// (foo.ts -> foo.spec.ts / foo.spec.tsx). Playwright tests (*.pw.tsx) deliberately do not count —
// they produce no vitest coverage.
function hasCoLocatedSpec(file: string): boolean {
  const base = file.slice(0, file.lastIndexOf('.'));
  return fs.existsSync(`${ base }.spec.ts`) || fs.existsSync(`${ base }.spec.tsx`);
}

// The CRAP (coverage) half applies to a JSX-less logic file always, and to a JSX component only
// when it has a co-located vitest spec — otherwise a component (covered, if at all, by Playwright
// visual tests that emit no vitest coverage) would read 0% and flood the report.
function coverageApplies(file: string, source: string): boolean {
  return !fileContainsJsx(source, file) || hasCoLocatedSpec(file);
}

// Focused mode: score every function in the given files, no diff-scoping (spec FR11). Coverage is
// generated from the files' transitive importers (`related`), matching what diff/full would give.
function runFocusedMode(options: CliOptions): Array<ReportRow> {
  const displayPaths = options.focusPaths.map(normalizeDisplayPath);
  const sources = new Map(displayPaths.map((displayPath) => [ displayPath, readFile(displayPath) ] as const));
  const appliesTo = (displayPath: string): boolean => coverageApplies(displayPath, sources.get(displayPath) as string);

  // Generate coverage only for the files that get the CRAP half, and only run vitest if there are any.
  const relatedPaths = displayPaths.filter(appliesTo);
  const coverage = resolveCoverage(options, { mode: 'related', paths: relatedPaths }, relatedPaths.length > 0);

  return displayPaths.flatMap((displayPath) => buildFileRows(displayPath, sources.get(displayPath) as string, coverage, {
    thresholds: thresholdsOf(options),
    gate: () => true,
    coverageApplies: appliesTo(displayPath),
    // A logic/spec'd file absent from generated coverage is genuinely untested -> 0%, except when
    // the user supplied the report themselves (then absence is "no data", `—`).
    missingCoverageIsZero: options.coverageMode !== 'file',
  }));
}

// Full-repo mode (default): score every in-scope src/** function. Untested files are absent from
// the coverage report and scored 0%, so the report shows the whole CRAP distribution (ticket 04).
// The repo always has files that need coverage and generation runs the whole suite regardless, so
// there is no per-file skip to make here.
function runFullMode(options: CliOptions): Array<ReportRow> {
  const files = getAllSourceFiles().filter(isInScope);
  if (files.length === 0) return [];
  const coverage = resolveCoverage(options, { mode: 'full' }, true);

  return files.flatMap((file) => {
    const source = readFile(file);
    return buildFileRows(file, source, coverage, {
      thresholds: thresholdsOf(options),
      gate: () => true,
      coverageApplies: coverageApplies(file, source),
      missingCoverageIsZero: true,
    });
  });
}

// Diff mode: gate only functions a changed line falls within, across in-scope changed files
// (spec FR5). Untouched functions in a changed file are listed but never flagged.
function runDiffMode(options: CliOptions): Array<ReportRow> {
  const baseCommit = resolveBaseCommit(options.baseRef);
  const changedFiles = getChangedFiles(baseCommit).filter(isInScope).filter((file) => fs.existsSync(file));
  if (changedFiles.length === 0) return []; // nothing in scope: skip vitest entirely

  const sources = new Map(changedFiles.map((file) => [ file, readFile(file) ] as const));
  const appliesTo = (file: string): boolean => coverageApplies(file, sources.get(file) as string);
  // A change that touches nothing needing coverage (e.g. only JSX components without specs) skips
  // the vitest run entirely.
  const coverage = resolveCoverage(options, { mode: 'changed', since: baseCommit }, changedFiles.some(appliesTo));

  return changedFiles.flatMap((file) => {
    const changedRanges = getChangedLineRanges(baseCommit, file);
    return buildFileRows(file, sources.get(file) as string, coverage, {
      thresholds: thresholdsOf(options),
      gate: (fn) => rangesOverlap(changedRanges, fn.startLine, fn.endLine),
      coverageApplies: appliesTo(file),
      // A changed in-scope file missing from coverage is untested changed code -> 0% (spec FR).
      missingCoverageIsZero: true,
    });
  });
}

function selectRows(options: CliOptions): Array<ReportRow> {
  if (options.focusPaths.length > 0) return runFocusedMode(options);
  if (options.diffSelected) return runDiffMode(options);
  return runFullMode(options);
}

function main(): void {
  const options = parseArgs(process.argv.slice(2));
  const rows = selectRows(options);

  if (rows.length === 0) {
    console.log('No functions to check.');
    return;
  }

  console.log(formatTable(rows, thresholdsOf(options)));

  if (rows.some(isOffender)) {
    process.exitCode = 1;
  }
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
