/* eslint-disable no-console -- this is a CLI whose entire job is to print a report to stdout */
import fs from 'fs';

import { buildFileRows } from './analyze';
import { DEFAULT_BASE_REF, DEFAULT_MAX_COGNITIVE_BEHAVIOR, DEFAULT_MAX_COGNITIVE_JSX, DEFAULT_MAX_CRAP } from './config';
import { readCoverage } from './coverage';
import type { CoverageData } from './coverage';
import { getAllSourceFiles, getChangedFiles, getChangedLineRanges, rangesOverlap, resolveBaseCommit } from './diff';
import { generateCoverage } from './generate-coverage';
import type { CoverageRequest } from './generate-coverage';
import { githubAnnotations, stepSummary } from './github';
import { fileContainsJsx } from './jsx';
import type { ReportRow, Thresholds } from './report';
import { formatTable, isOffender } from './report';
import { isInScope } from './scope';

// The CLI has two independent axes, mirroring vitest: selection (which functions to score) and
// coverage source (how the CRAP half is fed). Any selection combines with any source; ./CONTEXT.md
// tabulates both. USAGE below is the flag reference.
type CoverageMode = 'generate' | 'file' | 'off';

interface CliOptions {
  baseRef: string;
  diffSelected: boolean;
  maxCognitiveJsx: number;
  maxCognitiveBehavior: number;
  maxCrap: number;
  coverageMode: CoverageMode;
  coverageFile: string | undefined; // set only when coverageMode === 'file'
  verbose: boolean;
  focusPaths: Array<string>;
}

const USAGE = `Usage:
  test:code-complexity [--max-cognitive <n>] [--max-cognitive-jsx <n>]
                       [--max-cognitive-behavior <n>] [--max-crap <n>]
                       [--coverage-file <path> | --no-coverage] [--verbose]
      Full-repo mode (default): score every in-scope function (src/** and tools/**).
      The readability gate is cognitive complexity, capped per function class:
      --max-cognitive-jsx for render bodies, --max-cognitive-behavior for handlers/hooks/utils;
      bare --max-cognitive sets both. --max-crap caps the CRAP score (cyclomatic × coverage).

  test:code-complexity <path...> [...]     Focused mode: score every function in the given files.

  test:code-complexity --changed[=<ref>] [--base <ref>] [...]
      Diff mode: gate only functions the diff touches vs the base ref (default origin/main).

  Coverage is generated by running vitest (scoped to the selection) unless --coverage-file supplies
  a prebuilt report (the CI path, skips vitest) or --no-coverage skips it (cognitive gate only).
  Vitest output is hidden by default; --verbose streams it live and adds the cyclomatic (CX) column.`;

// Cap values are positive integers; anything else is a typo worth failing on rather than silently
// defaulting.
function readCap(flag: string, raw: string): number {
  const value = Number(raw);
  if (!Number.isFinite(value) || value < 1) throw new Error(`Invalid value for ${ flag }: ${ raw }`);
  return value;
}

// One flag's behaviour, discriminated by how it takes its value:
//   'switch'   — no value at all (--verbose)
//   'value'    — required, from `--flag=value` or the following token (--max-crap)
//   'optional' — inline-only and optional (--changed[=<ref>]); a bare --changed keeps the default
//                ref, and the flag must never swallow the following token, which in CI is another flag
type FlagSpec =
  { readonly kind: 'switch'; readonly apply: (options: CliOptions) => void } |
  { readonly kind: 'value'; readonly apply: (options: CliOptions, value: string) => void } |
  { readonly kind: 'optional'; readonly apply: (options: CliOptions, value: string | undefined) => void };

// The whole flag surface as data. Keeping it a lookup rather than an if/else chain is what leaves
// readability budget for the next flag, and it removes the prefix-shadowing hazard a `startsWith`
// chain has (`--max-cognitive` matching `--max-cognitive-jsx` unless the arms are ordered just so).
const FLAGS: ReadonlyMap<string, FlagSpec> = new Map<string, FlagSpec>([
  [ '--help', { kind: 'switch', apply: () => {
    console.log(USAGE);
    process.exit(0);
  } } ],
  [ '-h', { kind: 'switch', apply: () => {
    console.log(USAGE);
    process.exit(0);
  } } ],
  [ '--verbose', { kind: 'switch', apply: (options) => {
    options.verbose = true;
  } } ],
  [ '--no-coverage', { kind: 'switch', apply: (options) => {
    options.coverageMode = 'off';
  } } ],
  [ '--coverage-file', { kind: 'value', apply: (options, value) => {
    options.coverageMode = 'file';
    options.coverageFile = value;
  } } ],
  [ '--changed', { kind: 'optional', apply: (options, value) => {
    options.diffSelected = true;
    if (value !== undefined) options.baseRef = value;
  } } ],
  [ '--base', { kind: 'value', apply: (options, value) => {
    options.diffSelected = true;
    options.baseRef = value;
  } } ],
  [ '--max-cognitive-jsx', { kind: 'value', apply: (options, value) => {
    options.maxCognitiveJsx = readCap('--max-cognitive-jsx', value);
  } } ],
  [ '--max-cognitive-behavior', { kind: 'value', apply: (options, value) => {
    options.maxCognitiveBehavior = readCap('--max-cognitive-behavior', value);
  } } ],
  // Bare --max-cognitive is a global that clamps both per-class caps.
  [ '--max-cognitive', { kind: 'value', apply: (options, value) => {
    const cap = readCap('--max-cognitive', value);
    options.maxCognitiveJsx = cap;
    options.maxCognitiveBehavior = cap;
  } } ],
  [ '--max-crap', { kind: 'value', apply: (options, value) => {
    options.maxCrap = readCap('--max-crap', value);
  } } ],
]);

// Split a token into its flag name and inline value: `--flag=value` splits at the first `=`, a bare
// `--flag` has no inline value.
function splitFlag(arg: string): { readonly name: string; readonly inline: string | undefined } {
  const equals = arg.indexOf('=');
  if (equals === -1) return { name: arg, inline: undefined };
  return { name: arg.slice(0, equals), inline: arg.slice(equals + 1) };
}

// Apply one argv token to `options`, returning how many tokens it consumed — 2 when a value flag
// took the following token, 1 otherwise. This is the validation half: it resolves the value form,
// rejects unknown flags, and rejects a missing or unwanted value. `parseArgs` below is the reading
// half and does nothing but walk the cursor.
function applyArg(arg: string, next: string | undefined, options: CliOptions): number {
  if (!arg.startsWith('-')) {
    options.focusPaths.push(arg);
    return 1;
  }

  const { name, inline } = splitFlag(arg);
  const spec = FLAGS.get(name);
  if (spec === undefined) throw new Error(`Unknown flag: ${ name }\n${ USAGE }`);

  if (spec.kind === 'optional') {
    spec.apply(options, inline);
    return 1;
  }
  if (spec.kind === 'switch') {
    if (inline !== undefined) throw new Error(`${ name } takes no value`);
    spec.apply(options);
    return 1;
  }

  const value = inline ?? next;
  if (value === undefined) throw new Error(`Missing value for ${ name }`);
  spec.apply(options, value);
  return inline === undefined ? 2 : 1;
}

export function parseArgs(argv: ReadonlyArray<string>): CliOptions {
  const options: CliOptions = {
    baseRef: DEFAULT_BASE_REF,
    diffSelected: false,
    maxCognitiveJsx: DEFAULT_MAX_COGNITIVE_JSX,
    maxCognitiveBehavior: DEFAULT_MAX_COGNITIVE_BEHAVIOR,
    maxCrap: DEFAULT_MAX_CRAP,
    coverageMode: 'generate',
    coverageFile: undefined,
    verbose: false,
    focusPaths: [],
  };

  let index = 0;
  while (index < argv.length) {
    index += applyArg(argv[index], argv[index + 1], options);
  }

  return options;
}

function normalizeDisplayPath(filePath: string): string {
  return filePath.replace(/\\/g, '/').replace(/^\.\//, '');
}

function readFile(filePath: string): string {
  return fs.readFileSync(filePath, 'utf8');
}

function thresholdsOf(options: CliOptions): Thresholds {
  return {
    maxCognitiveJsx: options.maxCognitiveJsx,
    maxCognitiveBehavior: options.maxCognitiveBehavior,
    maxCrap: options.maxCrap,
  };
}

// Resolve coverage from the chosen mode. `request` steers generation; it is ignored for 'file' and
// 'off'. `anyNeedsCoverage` short-circuits generation: when no file in the selection needs coverage
// generated (see fileNeedsCoverage) there is nothing coverage could inform, so we skip vitest and
// return null instead of running it for numbers that would be discarded.
function resolveCoverage(options: CliOptions, request: CoverageRequest, anyNeedsCoverage: boolean): CoverageData | null {
  switch (options.coverageMode) {
    case 'off':
      return null;
    case 'file':
      // coverageFile is always set when the mode is 'file' (parseArgs reads its value).
      return readCoverage(options.coverageFile as string);
    case 'generate':
      return anyNeedsCoverage ? generateCoverage(request, { verbose: options.verbose }) : null;
  }
}

// Whether a source file has a co-located vitest spec, by naming convention
// (foo.ts -> foo.spec.ts / foo.spec.tsx). Playwright tests (*.pw.tsx) do not count: no vitest
// coverage comes out of them.
function hasCoLocatedSpec(file: string): boolean {
  const base = file.slice(0, file.lastIndexOf('.'));
  return fs.existsSync(`${ base }.spec.ts`) || fs.existsSync(`${ base }.spec.tsx`);
}

// Whether a file needs vitest coverage generated for it: a JSX-less logic file always does; a JSX
// component only when it has a co-located vitest spec. This drives only the generation scope
// (./CONTEXT.md); per-function CRAP applicability is decided in analyze.ts.
function fileNeedsCoverage(file: string, source: string): boolean {
  return !fileContainsJsx(source, file) || hasCoLocatedSpec(file);
}

// Focused mode: score every function in the given files, no diff-scoping. Coverage comes from the
// files' transitive importers (`related`), matching what diff/full would give.
function runFocusedMode(options: CliOptions): Array<ReportRow> {
  const displayPaths = options.focusPaths.map(normalizeDisplayPath);
  const sources = new Map(displayPaths.map((displayPath) => [ displayPath, readFile(displayPath) ] as const));
  const needsCoverage = (displayPath: string): boolean => fileNeedsCoverage(displayPath, sources.get(displayPath) as string);

  // Generate coverage only for the files that need it, and only run vitest if there are any.
  const relatedPaths = displayPaths.filter(needsCoverage);
  const coverage = resolveCoverage(options, { mode: 'related', paths: relatedPaths }, relatedPaths.length > 0);

  return displayPaths.flatMap((displayPath) => buildFileRows(displayPath, sources.get(displayPath) as string, coverage, {
    thresholds: thresholdsOf(options),
    gate: () => true,
    // The one mode where a missing entry may just mean the hand-passed report predates the file.
    missingCoverageIsZero: options.coverageMode !== 'file',
  }));
}

// Full-repo mode (default): score every in-scope function, across both allowlisted roots. This is
// the mode threshold calibration runs (./CALIBRATION.md). The repo always has files that need
// coverage and generation runs the whole suite regardless, so there is no per-file skip here.
function runFullMode(options: CliOptions): Array<ReportRow> {
  const files = getAllSourceFiles();
  if (files.length === 0) return [];
  const coverage = resolveCoverage(options, { mode: 'full' }, true);

  return files.flatMap((file) => {
    const source = readFile(file);
    return buildFileRows(file, source, coverage, {
      thresholds: thresholdsOf(options),
      gate: () => true,
      missingCoverageIsZero: true,
    });
  });
}

// Diff mode: gate only functions a changed line falls within, across in-scope changed files.
// Untouched functions in a changed file are listed but never flagged.
function runDiffMode(options: CliOptions): Array<ReportRow> {
  const baseCommit = resolveBaseCommit(options.baseRef);
  const changedFiles = getChangedFiles(baseCommit).filter(isInScope).filter((file) => fs.existsSync(file));
  if (changedFiles.length === 0) return []; // nothing in scope: skip vitest entirely

  const sources = new Map(changedFiles.map((file) => [ file, readFile(file) ] as const));
  const needsCoverage = (file: string): boolean => fileNeedsCoverage(file, sources.get(file) as string);
  // A change that touches nothing needing coverage (e.g. only JSX components without specs) skips
  // the vitest run entirely.
  const coverage = resolveCoverage(options, { mode: 'changed', since: baseCommit }, changedFiles.some(needsCoverage));

  return changedFiles.flatMap((file) => {
    const changedRanges = getChangedLineRanges(baseCommit, file);
    return buildFileRows(file, sources.get(file) as string, coverage, {
      thresholds: thresholdsOf(options),
      gate: (fn) => rangesOverlap(changedRanges, fn.startLine, fn.endLine),
      // A changed behavior function missing from coverage is untested changed code -> 0%.
      missingCoverageIsZero: true,
    });
  });
}

function selectRows(options: CliOptions): Array<ReportRow> {
  if (options.focusPaths.length > 0) return runFocusedMode(options);
  if (options.diffSelected) return runDiffMode(options);
  return runFullMode(options);
}

// Under $GITHUB_ACTIONS, add the two CI outputs: `::error` annotations that surface each offender
// inline on the PR diff, and the full table written to the job summary. The plain-stdout table has
// already been printed.
function emitGithubActionsOutput(rows: ReadonlyArray<ReportRow>, thresholds: Thresholds, table: string): void {
  for (const annotation of githubAnnotations(rows, thresholds)) console.log(annotation);
  // eslint-disable-next-line no-restricted-properties -- Node CLI reading a CI-provided path, not an app env var
  const summaryPath = process.env.GITHUB_STEP_SUMMARY;
  if (summaryPath) fs.appendFileSync(summaryPath, `${ stepSummary(table) }\n`);
}

function main(): void {
  const options = parseArgs(process.argv.slice(2));
  const rows = selectRows(options);

  if (rows.length === 0) {
    console.log('No functions to check.');
    return;
  }

  const table = formatTable(rows, thresholdsOf(options), options.verbose);
  console.log(table);

  // eslint-disable-next-line no-restricted-properties -- Node CLI detecting the CI runtime, not an app env var
  if (process.env.GITHUB_ACTIONS) emitGithubActionsOutput(rows, thresholdsOf(options), table);

  if (rows.some(isOffender)) {
    process.exitCode = 1;
  }
}

// run.sh always executes the compiled `tools/code-complexity/dist/index.js`, so that path is what
// marks this module as the process entry point. The guard exists so `index.spec.ts` can import
// parseArgs without kicking off a whole report run — under vitest the entry is vitest's own binary.
const CLI_ENTRY_PATH = 'code-complexity/dist/index.js';

function isProcessEntryPoint(): boolean {
  const entry = process.argv[1]?.replace(/\\/g, '/');
  return entry !== undefined && entry.endsWith(CLI_ENTRY_PATH);
}

if (isProcessEntryPoint()) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
