import type CspDev from 'csp-dev';

import config from 'configs/app';

export function ylideRpcs(): CspDev.DirectiveDescriptor {
  if (!config.features.forum.isEnabled) {
    return {};
  }

  return {
    'connect-src': [
      '*.ylide.io',
      '*.terminet.io',
      '*.blockpi.network',
      '*.blockscout.com',
      '*.gateway.pokt.network',
      '*.linkpool.io',
      '*.rpcfast.com',
      '*.public.blastapi.io',
      '*.binance.org',
      '*.defibit.io',
      '*.ninicoin.io',
      '*.nodereal.io',
      '*.bwarelabs.com',
      '*.bwarelabs.com',
      '*.fandom.finance',
      '*.api.onfinality.io',
      '*.moonbeam.network',
      '*.moonscan.io',
      '*.fantom.network',
      '*.mytokenpocket.vip',
      'evm.cronos.org',
      'cronos-rpc.heavenswail.one',
      'cronosrpc-1.xstaking.sg',
      'cronos-rpc.elk.finance',
      'api.mycryptoapi.com',
      'rpc.flashbots.net',
      'rpc.ankr.com',
      '1rpc.io',
      'lineascan.build',
      'basescan.org',
      'cronoscan.com',
      'cloudflare-eth.com',
      'nodes.mewapi.io',
      'mainnet.eth.cloud.ava.do',
      'ethereumnodelight.app.runonflux.io',
      'api.bitstack.com',
      'eth-mainnet.unifra.io',
      'api.securerpc.com',
      'etherscan.io',
      'bscrpc.com',
      'rpc-bsc.bnb48.club',
      'bscscan.com',
      'arb1.arbitrum.io',
      'arbiscan.io',
      'api.avax.network',
      'snowtrace.io',
      'mainnet.optimism.io',
      'optimistic.etherscan.io',
      'polygon-rpc.com',
      'rpc-mainnet.matic.network',
      'matic-mainnet.chainstacklabs.com',
      'rpc-mainnet.maticvigil.com',
      'rpc-mainnet.matic.quiknode.pro',
      'polygon-bor.publicnode.com',
      'matic.slingshot.finance',
      'polygonscan.com',
      'rpc.ftm.tools',
      'ftmscan.com',
      'public-node-api.klaytnapi.com',
      'scope.klaytn.com',
      'rpc.gnosischain.com',
      'rpc.ap-southeast-1.gateway.fm',
      'gnosisscan.io',
      'mainnet.aurora.dev',
      'aurorascan.dev',
      'forno.celo.org',
      'celoscan.io',
      'andromeda.metis.io',
      'andromeda-explorer.metis.io',
      'wss://*.ylide.io',
      'wss://*.alchemy.com',
      'wss://*.infura.io',
      'wss://*.nodereal.io',
      'wss://rpc.gnosischain.com',
      'wss://forno.celo.org',
      'wss://wss.api.moonbeam.network',
    ],
  };
}
