name: Release

on:
    workflow_dispatch:
    release:
        types: [ released ]

jobs:
    remove_prerelease_label:
        name: Remove pre-release label from PRs and issues
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: write
            pull-requests: write
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4

            -   name: Install pnpm
                uses: pnpm/action-setup@v6
                with:
                    version: 12.4.1
                    cache: true

            -   name: Setup node
                uses: actions/setup-node@v4
                with:
                    node-version: 24.21.0
                    cache: 'pnpm'

            -   name: Install dependencies
                run: pnpm install --frozen-lockfile

            -   name: Remove label
                run: pnpm release label "$TAG" --remove=pre-release
                env:
                    GH_TOKEN: ${{ github.token }}
                    TAG: ${{ github.ref_name }}

    label_released_issues:
        name: Label released issues
        uses: './.github/workflows/label-issues-in-release.yml'
        with:
            tag: ${{ github.ref_name }}
            label_name: ${{ github.ref_name }}
            label_description: Release ${{ github.ref_name }}
        secrets: inherit
        permissions:
            contents: read
            issues: write
            pull-requests: write

    update_project_cards:
        name: Update project tasks statuses
        needs: label_released_issues
        uses: './.github/workflows/update-project-cards.yml'
        with:
            project_name: ${{ vars.PROJECT_NAME }}
            field_name: Status
            field_value: Released
            issues: ${{ needs.label_released_issues.outputs.issues }}
        secrets: inherit
        permissions:
            issues: read

    publish_image:
        name: Publish Docker image
        uses: './.github/workflows/publish-image.yml'
        secrets: inherit
        with:
            platforms: linux/amd64,linux/arm64/v8
            # NOTE: by default the image will be built with type=ref,event=tag; so we need to specify it here
            tags: |
                type=raw,value=latest
        permissions:
            contents: read
            packages: write

    publish_toolkit:
        name: Publish toolkit package to NPM
        uses: './.github/workflows/toolkit-npm-publisher.yml'
        secrets: inherit
        with:
            version: ${{ github.ref_name }}
        permissions:
            contents: read
            id-token: write
