name: Sync ENV variables docs

on:
    workflow_dispatch:

jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        steps:
            -   name: Copy files to Blockscout Docs repository
                uses: lubu12/copy-files-to-repository@v1
                env:
                    API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
                with:
                    source-files: 'docs/ENVS.md docs/DEPRECATED_ENVS.md'
                    destination-username: 'blockscout-bot'
                    destination-repository: 'blockscout/docs'
                    destination-directory: 'docs/setup/env-variables/frontend-common-envs'
                    commit-email: 'tom@blockscout.com'
